import 'assessment_models.dart';

final assessmentTeachers = <AssessmentTeacher>[
  const AssessmentTeacher(
    id: 'T001',
    name: 'Dr. Sarah Ahmed',
    email: 'sarah.ahmed@university.edu',
    password: '',
    courseIds: ['C001', 'C002'],
  ),
  const AssessmentTeacher(
    id: 'T002',
    name: 'Prof. Muhammad Khan',
    email: 'm.khan@university.edu',
    password: '',
    courseIds: ['C003', 'C004'],
  ),
  const AssessmentTeacher(
    id: 'T003',
    name: 'Dr. Ayesha Ali',
    email: 'ayesha.ali@university.edu',
    password: '',
    courseIds: ['C005', 'C006'],
  ),
  const AssessmentTeacher(
    id: 'T004',
    name: 'Dr. Fatima Malik',
    email: 'fatima.malik@university.edu',
    password: '',
    courseIds: ['C009', 'C010'],
  ),
];

final assessmentCourses = <AssessmentCourse>[
  const AssessmentCourse(
    id: 'C001',
    courseName: 'Data Structures',
    courseCode: 'CS-201',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 45,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Dr. Sarah Ahmed',
  ),
  const AssessmentCourse(
    id: 'C002',
    courseName: 'Algorithms',
    courseCode: 'CS-301',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 38,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Dr. Sarah Ahmed',
  ),
  const AssessmentCourse(
    id: 'C003',
    courseName: 'Database Systems',
    courseCode: 'CS-302',
    credits: 4,
    semester: '5',
    section: 'B',
    enrolledStudents: 42,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Prof. Muhammad Khan',
  ),
  const AssessmentCourse(
    id: 'C004',
    courseName: 'Software Engineering',
    courseCode: 'SE-401',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 35,
    program: 'BSSE',
    session: 'S26',
    instructor: 'Prof. Muhammad Khan',
  ),
  const AssessmentCourse(
    id: 'C005',
    courseName: 'Operating Systems',
    courseCode: 'CS-401',
    credits: 4,
    semester: '7',
    section: 'A',
    enrolledStudents: 40,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Dr. Ayesha Ali',
  ),
  const AssessmentCourse(
    id: 'C006',
    courseName: 'Computer Networks',
    courseCode: 'CS-402',
    credits: 3,
    semester: '7',
    section: 'B',
    enrolledStudents: 36,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Dr. Ayesha Ali',
  ),
  const AssessmentCourse(
    id: 'C009',
    courseName: 'Web Development',
    courseCode: 'SE-301',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 44,
    program: 'BSSE',
    session: 'S26',
    instructor: 'Dr. Fatima Malik',
  ),
  const AssessmentCourse(
    id: 'C010',
    courseName: 'Mobile App Development',
    courseCode: 'SE-401',
    credits: 3,
    semester: '7',
    section: 'B',
    enrolledStudents: 30,
    program: 'BSSE',
    session: 'S26',
    instructor: 'Dr. Fatima Malik',
  ),
  const AssessmentCourse(
    id: 'C012',
    courseName: 'Information Security',
    courseCode: 'CS-503',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 25,
    program: 'MPCS',
    session: 'S26',
    instructor: 'Prof. Usman Shah',
  ),
  const AssessmentCourse(
    id: 'C016',
    courseName: 'Compiler Construction',
    courseCode: 'CS-404',
    credits: 3,
    semester: '7',
    section: 'D',
    enrolledStudents: 31,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Prof. Ali Raza',
  ),
];

final assessmentStudents = <AssessmentStudent>[
  const AssessmentStudent(
    id: 'S001',
    name: 'Ahmad Hassan',
    studentId: 'BSCS-S26-001',
    program: 'BSCS',
    session: 'S26',
    semester: '3',
    section: 'A',
    email: 'ahmad.hassan@student.edu',
  ),
  const AssessmentStudent(
    id: 'S002',
    name: 'Fatima Khan',
    studentId: 'BSCS-S26-002',
    program: 'BSCS',
    session: 'S26',
    semester: '3',
    section: 'A',
    email: 'fatima.khan@student.edu',
  ),
  const AssessmentStudent(
    id: 'S003',
    name: 'Usman Ali',
    studentId: 'BSCS-S26-003',
    program: 'BSCS',
    session: 'S26',
    semester: '5',
    section: 'A',
    email: 'usman.ali@student.edu',
  ),
  const AssessmentStudent(
    id: 'S004',
    name: 'Ayesha Ahmed',
    studentId: 'BSCS-S26-004',
    program: 'BSCS',
    session: 'S26',
    semester: '5',
    section: 'B',
    email: 'ayesha.ahmed@student.edu',
  ),
  const AssessmentStudent(
    id: 'S005',
    name: 'Hassan Raza',
    studentId: 'BSSE-S26-005',
    program: 'BSSE',
    session: 'S26',
    semester: '7',
    section: 'A',
    email: 'hassan.raza@student.edu',
  ),
  const AssessmentStudent(
    id: 'S008',
    name: 'Maryam Siddiqui',
    studentId: 'BSSE-S26-008',
    program: 'BSSE',
    session: 'S26',
    semester: '5',
    section: 'A',
    email: 'maryam.siddiqui@student.edu',
  ),
  const AssessmentStudent(
    id: 'S010',
    name: 'Sana Tariq',
    studentId: 'MPCS-S26-010',
    program: 'MPCS',
    session: 'S26',
    semester: '2',
    section: 'A',
    email: 'sana.tariq@student.edu',
  ),
];

final assessmentSettings = const AssessmentSettings(
  randomizeQuestions: true,
  randomizeOptions: true,
  oneAttemptOnly: true,
  autoSubmit: true,
  showResultAfterSubmission: false,
  manualGrading: false,
);

final mockAssessments = <Assessment>[
  Assessment(
    id: 'A001',
    title: 'Data Structures - Quiz 1',
    type: AssessmentType.quiz,
    courseId: 'C001',
    program: 'BSCS',
    semester: '3',
    section: 'A',
    durationMinutes: 30,
    totalMarks: 20,
    startTime: DateTime(2026, 5, 22, 10),
    endTime: DateTime(2026, 5, 22, 10, 30),
    instructions:
        'Answer all questions. Each question carries equal marks. No negative marking.',
    questions: const [
      AssessmentQuestion(
        id: 'Q001',
        type: QuestionType.mcq,
        question: 'What is the time complexity of binary search?',
        options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
        correctAnswer: 'O(log n)',
        marks: 2,
      ),
      AssessmentQuestion(
        id: 'Q002',
        type: QuestionType.mcq,
        question: 'Which data structure uses LIFO principle?',
        options: ['Queue', 'Stack', 'Array', 'Tree'],
        correctAnswer: 'Stack',
        marks: 2,
      ),
      AssessmentQuestion(
        id: 'Q003',
        type: QuestionType.trueFalse,
        question: 'A linked list supports direct random access.',
        correctAnswer: 'False',
        marks: 2,
      ),
      AssessmentQuestion(
        id: 'Q004',
        type: QuestionType.shortAnswer,
        question: 'Write one difference between an array and a linked list.',
        marks: 4,
      ),
      AssessmentQuestion(
        id: 'Q005',
        type: QuestionType.longAnswer,
        question: 'Explain stack operations with a small classroom example.',
        marks: 10,
      ),
    ],
    settings: assessmentSettings,
    status: AssessmentStatus.active,
    qrCode: 'ASSESS_A001_C001_S26_3A',
  ),
];

final mockSubmissions = <AssessmentSubmission>[
  AssessmentSubmission(
    id: 'SUB001',
    assessmentId: 'A001',
    studentId: 'S001',
    status: AttemptStatus.submitted,
    startedAt: DateTime(2026, 5, 22, 10),
    submittedAt: DateTime(2026, 5, 22, 10, 25),
    answers: const {},
    marks: 18,
    warningCount: 0,
    flags: const [],
    progress: 100,
    lastActivity: DateTime(2026, 5, 22, 10, 25),
  ),
  AssessmentSubmission(
    id: 'SUB002',
    assessmentId: 'A001',
    studentId: 'S002',
    status: AttemptStatus.inProgress,
    startedAt: DateTime(2026, 5, 22, 10, 2),
    answers: const {},
    warningCount: 1,
    flags: const ['App switch detected'],
    progress: 60,
    lastActivity: DateTime(2026, 5, 22, 10, 15),
  ),
  AssessmentSubmission(
    id: 'SUB003',
    assessmentId: 'A001',
    studentId: 'S004',
    status: AttemptStatus.flagged,
    startedAt: DateTime(2026, 5, 22, 10, 1),
    answers: const {},
    warningCount: 3,
    flags: const ['App switch detected', 'Screenshot attempt', 'Copy attempt'],
    progress: 40,
    lastActivity: DateTime(2026, 5, 22, 10, 12),
  ),
];
