import 'assessment_models.dart';

final assessmentTeachers = <AssessmentTeacher>[
  const AssessmentTeacher(
    id: 'T001',
    name: 'Dr. Sarah Ahmed',
    email: 'sarah.ahmed@university.edu',
    password: '',
    courseIds: ['C001', 'C002'],
  ),
  const AssessmentTeacher(
    id: 'T002',
    name: 'Prof. Muhammad Khan',
    email: 'm.khan@university.edu',
    password: '',
    courseIds: ['C003', 'C004'],
  ),
  const AssessmentTeacher(
    id: 'T003',
    name: 'Dr. Ayesha Ali',
    email: 'ayesha.ali@university.edu',
    password: '',
    courseIds: ['C005', 'C006'],
  ),
  const AssessmentTeacher(
    id: 'T004',
    name: 'Dr. Fatima Malik',
    email: 'fatima.malik@university.edu',
    password: '',
    courseIds: ['C009', 'C010'],
  ),
];

final assessmentCourses = <AssessmentCourse>[
  const AssessmentCourse(
    id: 'C001',
    courseName: 'Data Structures',
    courseCode: 'CS-201',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 45,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Dr. Sarah Ahmed',
  ),
  const AssessmentCourse(
    id: 'C002',
    courseName: 'Algorithms',
    courseCode: 'CS-301',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 38,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Dr. Sarah Ahmed',
  ),
  const AssessmentCourse(
    id: 'C003',
    courseName: 'Database Systems',
    courseCode: 'CS-302',
    credits: 4,
    semester: '5',
    section: 'B',
    enrolledStudents: 42,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Prof. Muhammad Khan',
  ),
  const AssessmentCourse(
    id: 'C004',
    courseName: 'Software Engineering',
    courseCode: 'SE-401',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 35,
    program: 'BSSE',
    session: 'S26',
    instructor: 'Prof. Muhammad Khan',
  ),
  const AssessmentCourse(
    id: 'C005',
    courseName: 'Operating Systems',
    courseCode: 'CS-401',
    credits: 4,
    semester: '7',
    section: 'A',
    enrolledStudents: 40,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Dr. Ayesha Ali',
  ),
  const AssessmentCourse(
    id: 'C006',
    courseName: 'Computer Networks',
    courseCode: 'CS-402',
    credits: 3,
    semester: '7',
    section: 'B',
    enrolledStudents: 36,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Dr. Ayesha Ali',
  ),
  const AssessmentCourse(
    id: 'C009',
    courseName: 'Web Development',
    courseCode: 'SE-301',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 44,
    program: 'BSSE',
    session: 'S26',
    instructor: 'Dr. Fatima Malik',
  ),
  const AssessmentCourse(
    id: 'C010',
    courseName: 'Mobile App Development',
    courseCode: 'SE-401',
    credits: 3,
    semester: '7',
    section: 'B',
    enrolledStudents: 30,
    program: 'BSSE',
    session: 'S26',
    instructor: 'Dr. Fatima Malik',
  ),
  const AssessmentCourse(
    id: 'C012',
    courseName: 'Information Security',
    courseCode: 'CS-503',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 25,
    program: 'MPCS',
    session: 'S26',
    instructor: 'Prof. Usman Shah',
  ),
  const AssessmentCourse(
    id: 'C016',
    courseName: 'Compiler Construction',
    courseCode: 'CS-404',
    credits: 3,
    semester: '7',
    section: 'D',
    enrolledStudents: 31,
    program: 'BSCS',
    session: 'S26',
    instructor: 'Prof. Ali Raza',
  ),
];

final assessmentStudents = <AssessmentStudent>[
  const AssessmentStudent(
    id: 'S001',
    name: 'Ahmad Hassan',
    studentId: 'BSCS-S26-001',
    program: 'BSCS',
    session: 'S26',
    semester: '3',
    section: 'A',
    email: 'ahmad.hassan@student.edu',
  ),
  const AssessmentStudent(
    id: 'S002',
    name: 'Fatima Khan',
    studentId: 'BSCS-S26-002',
    program: 'BSCS',
    session: 'S26',
    semester: '3',
    section: 'A',
    email: 'fatima.khan@student.edu',
  ),
  const AssessmentStudent(
    id: 'S003',
    name: 'Usman Ali',
    studentId: 'BSCS-S26-003',
    program: 'BSCS',
    session: 'S26',
    semester: '5',
    section: 'A',
    email: 'usman.ali@student.edu',
  ),
  const AssessmentStudent(
    id: 'S004',
    name: 'Ayesha Ahmed',
    studentId: 'BSCS-S26-004',
    program: 'BSCS',
    session: 'S26',
    semester: '5',
    section: 'B',
    email: 'ayesha.ahmed@student.edu',
  ),
  const AssessmentStudent(
    id: 'S005',
    name: 'Hassan Raza',
    studentId: 'BSSE-S26-005',
    program: 'BSSE',
    session: 'S26',
    semester: '7',
    section: 'A',
    email: 'hassan.raza@student.edu',
  ),
  const AssessmentStudent(
    id: 'S008',
    name: 'Maryam Siddiqui',
    studentId: 'BSSE-S26-008',
    program: 'BSSE',
    session: 'S26',
    semester: '5',
    section: 'A',
    email: 'maryam.siddiqui@student.edu',
  ),
  const AssessmentStudent(
    id: 'S010',
    name: 'Sana Tariq',
    studentId: 'MPCS-S26-010',
    program: 'MPCS',
    session: 'S26',
    semester: '2',
    section: 'A',
    email: 'sana.tariq@student.edu',
  ),
];

final assessmentSettings = const AssessmentSettings(
  randomizeQuestions: true,
  randomizeOptions: true,
  oneAttemptOnly: true,
  autoSubmit: true,
  showResultAfterSubmission: false,
  manualGrading: false,
);

// No pre-seeded assessments — teachers create them fresh in-app.
final mockAssessments = <Assessment>[];

// No pre-seeded submissions — they are created when students attempt.
final mockSubmissions = <AssessmentSubmission>[];
