import 'assessment_models.dart';

const registrationCourses = <AssessmentCourse>[
  AssessmentCourse(
    id: 'C001',
    courseName: 'ADDITIONAL MATH-I (FOR PRE-MEDICAL STUDENTS ONLY)',
    courseCode: 'AM101',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 23,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. SAJID ALI',
  ),
  AssessmentCourse(
    id: 'C002',
    courseName: 'FUNCTIONAL ENGLISH',
    courseCode: 'FE101',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 66,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. ABDUL AMAN',
  ),
  AssessmentCourse(
    id: 'C003',
    courseName: 'SOCIAL SCIENCE',
    courseCode: 'SS101',
    credits: 2,
    semester: '1',
    section: 'A',
    enrolledStudents: 66,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. SANA GUL',
  ),
  AssessmentCourse(
    id: 'C004',
    courseName: 'ISLAMIC STUDIES (RELIGIOUS EDUCATION)',
    courseCode: 'IS101',
    credits: 2,
    semester: '1',
    section: 'A',
    enrolledStudents: 65,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. INAMULLAH',
  ),
  AssessmentCourse(
    id: 'C005',
    courseName: 'QUANTITATIVE REASONING-I',
    courseCode: 'QR101',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 66,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. SAJID ALI',
  ),
  AssessmentCourse(
    id: 'C006',
    courseName: 'FAHM-E-QURAN',
    courseCode: 'FQ101',
    credits: 1,
    semester: '1',
    section: 'A',
    enrolledStudents: 66,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD UMAIR',
  ),
  AssessmentCourse(
    id: 'C007',
    courseName: 'PROGRAMMING FUNDAMENTALS',
    courseCode: 'PF101',
    credits: 4,
    semester: '1',
    section: 'A',
    enrolledStudents: 66,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MIR JAMAL UD DIN',
  ),
  AssessmentCourse(
    id: 'C008',
    courseName: 'APPLICATIONS OF INFORMATION AND COMMUNICATION TECHNOLOGIES',
    courseCode: 'AICT101',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 66,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. MUQADDAS YOUSAF',
  ),
  AssessmentCourse(
    id: 'C009',
    courseName: 'PROGRAMMING FUNDAMENTALS',
    courseCode: 'CSC112',
    credits: 4,
    semester: '1',
    section: 'A',
    enrolledStudents: 4,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MIR JAMAL UD DIN',
  ),
  AssessmentCourse(
    id: 'C010',
    courseName: 'PROGRAMMING FUNDAMENTALS',
    courseCode: 'CC110',
    credits: 4,
    semester: '1',
    section: 'A',
    enrolledStudents: 4,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MIR JAMAL UD DIN',
  ),
  AssessmentCourse(
    id: 'C011',
    courseName: 'CALCULUS & ANALYTICAL GEOMETRY',
    courseCode: 'MAT118',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 59,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. SAJID ALI',
  ),
  AssessmentCourse(
    id: 'C012',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CC120',
    credits: 4,
    semester: '2',
    section: 'A',
    enrolledStudents: 58,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. KINZA KHURSHID',
  ),
  AssessmentCourse(
    id: 'C013',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CC121',
    credits: 4,
    semester: '2',
    section: 'A',
    enrolledStudents: 57,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. AHSAN ZUBAIR',
  ),
  AssessmentCourse(
    id: 'C014',
    courseName: 'DIGITAL LOGIC DESIGN',
    courseCode: 'CC122',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 58,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. FAHAD ALI KHAN',
  ),
  AssessmentCourse(
    id: 'C015',
    courseName: 'EXPOSITORY WRITING',
    courseCode: 'GE120',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 58,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. ABDUL AMAN',
  ),
  AssessmentCourse(
    id: 'C016',
    courseName: 'LINEAR ALGEBRA',
    courseCode: 'MAT232',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 48,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. JAVERIA',
  ),
  AssessmentCourse(
    id: 'C017',
    courseName: 'MATHEMATICS-II',
    courseCode: 'MAT111',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 15,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. ROMANA',
  ),
  AssessmentCourse(
    id: 'C018',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CC120',
    credits: 4,
    semester: '2',
    section: 'B',
    enrolledStudents: 44,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. KINZA KHURSHID',
  ),
  AssessmentCourse(
    id: 'C019',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CC120',
    credits: 4,
    semester: '2',
    section: 'C',
    enrolledStudents: 38,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD SIBT UL HASSAN',
  ),
  AssessmentCourse(
    id: 'C020',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CC120',
    credits: 4,
    semester: '2',
    section: 'D',
    enrolledStudents: 49,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD SIBT UL HASSAN',
  ),
  AssessmentCourse(
    id: 'C021',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CC121',
    credits: 4,
    semester: '2',
    section: 'B',
    enrolledStudents: 45,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD IMRAN KHAN',
  ),
  AssessmentCourse(
    id: 'C022',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CC121',
    credits: 4,
    semester: '2',
    section: 'C',
    enrolledStudents: 40,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD IMRAN KHAN',
  ),
  AssessmentCourse(
    id: 'C023',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CC121',
    credits: 4,
    semester: '2',
    section: 'D',
    enrolledStudents: 50,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD IMRAN KHAN',
  ),
  AssessmentCourse(
    id: 'C024',
    courseName: 'DIGITAL LOGIC DESIGN',
    courseCode: 'CC122',
    credits: 3,
    semester: '2',
    section: 'B',
    enrolledStudents: 45,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. FAHAD ALI KHAN',
  ),
  AssessmentCourse(
    id: 'C025',
    courseName: 'DIGITAL LOGIC DESIGN',
    courseCode: 'CC122',
    credits: 3,
    semester: '2',
    section: 'C',
    enrolledStudents: 40,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. FAHAD ALI KHAN',
  ),
  AssessmentCourse(
    id: 'C026',
    courseName: 'DIGITAL LOGIC DESIGN',
    courseCode: 'CC122',
    credits: 3,
    semester: '2',
    section: 'D',
    enrolledStudents: 49,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. HADIYA ALI',
  ),
  AssessmentCourse(
    id: 'C027',
    courseName: 'EXPOSITORY WRITING',
    courseCode: 'GE120',
    credits: 3,
    semester: '2',
    section: 'B',
    enrolledStudents: 45,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. ABDUL AMAN',
  ),
  AssessmentCourse(
    id: 'C028',
    courseName: 'EXPOSITORY WRITING',
    courseCode: 'GE120',
    credits: 3,
    semester: '2',
    section: 'C',
    enrolledStudents: 40,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. ABDUL AMAN',
  ),
  AssessmentCourse(
    id: 'C029',
    courseName: 'EXPOSITORY WRITING',
    courseCode: 'GE120',
    credits: 3,
    semester: '2',
    section: 'D',
    enrolledStudents: 49,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. FATIMA MALIK',
  ),
  AssessmentCourse(
    id: 'C030',
    courseName: 'LINEAR ALGEBRA',
    courseCode: 'MAT232',
    credits: 3,
    semester: '2',
    section: 'B',
    enrolledStudents: 26,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. JAVERIA',
  ),
  AssessmentCourse(
    id: 'C031',
    courseName: 'LINEAR ALGEBRA',
    courseCode: 'MAT232',
    credits: 3,
    semester: '2',
    section: 'C',
    enrolledStudents: 26,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. JAVERIA',
  ),
  AssessmentCourse(
    id: 'C032',
    courseName: 'LINEAR ALGEBRA',
    courseCode: 'MAT232',
    credits: 3,
    semester: '2',
    section: 'D',
    enrolledStudents: 38,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. SAJID ALI',
  ),
  AssessmentCourse(
    id: 'C033',
    courseName: 'MATHEMATICS-II',
    courseCode: 'MAT111',
    credits: 3,
    semester: '2',
    section: 'B',
    enrolledStudents: 12,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. ROMANA',
  ),
  AssessmentCourse(
    id: 'C034',
    courseName: 'MATHEMATICS-II',
    courseCode: 'MAT111',
    credits: 3,
    semester: '2',
    section: 'C',
    enrolledStudents: 13,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. ROMANA',
  ),
  AssessmentCourse(
    id: 'C035',
    courseName: 'MATHEMATICS-II',
    courseCode: 'MAT111',
    credits: 3,
    semester: '2',
    section: 'D',
    enrolledStudents: 7,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. ROMANA',
  ),
  AssessmentCourse(
    id: 'C036',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CSC241',
    credits: 4,
    semester: '2',
    section: 'D',
    enrolledStudents: 1,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD IMRAN KHAN',
  ),
  AssessmentCourse(
    id: 'C037',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CSC121',
    credits: 4,
    semester: '2',
    section: 'D',
    enrolledStudents: 2,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD SIBT UL HASSAN',
  ),
  AssessmentCourse(
    id: 'C038',
    courseName: 'DIGITAL LOGIC DESIGN',
    courseCode: 'CSC232',
    credits: 4,
    semester: '2',
    section: 'D',
    enrolledStudents: 2,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. HADIYA ALI',
  ),
  AssessmentCourse(
    id: 'C039',
    courseName: 'DISCRETE STRUCTURES',
    courseCode: 'GE101',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 54,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. AYESHA ASLAM',
  ),
  AssessmentCourse(
    id: 'C040',
    courseName: 'MULTIVARIABLE CALCULUS',
    courseCode: 'MAT237',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 56,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. RUKHSANA JABEEN',
  ),
  AssessmentCourse(
    id: 'C041',
    courseName: 'SOFTWARE ENGINEERING',
    courseCode: 'CC214',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 54,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. NAVEEDA BIBI',
  ),
  AssessmentCourse(
    id: 'C042',
    courseName: 'COMPUTER NETWORKS',
    courseCode: 'CC213',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 55,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. HADIYA ALI',
  ),
  AssessmentCourse(
    id: 'C043',
    courseName: 'DATA STRUCTURES',
    courseCode: 'CC210',
    credits: 4,
    semester: '3',
    section: 'A',
    enrolledStudents: 53,
    program: 'BSCS',
    session: 'S26',
    instructor: 'SOHAIR SULTAN',
  ),
  AssessmentCourse(
    id: 'C044',
    courseName: 'ISLAMIC STUDIES',
    courseCode: 'GE220',
    credits: 2,
    semester: '3',
    section: 'A',
    enrolledStudents: 53,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. INAMULLAH',
  ),
  AssessmentCourse(
    id: 'C045',
    courseName: 'DISCRETE STRUCTURES',
    courseCode: 'CSC123',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 13,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. AYESHA ASLAM',
  ),
  AssessmentCourse(
    id: 'C046',
    courseName: 'SOFTWARE ENGINEERING',
    courseCode: 'CSC122',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 4,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. NAVEEDA BIBI',
  ),
  AssessmentCourse(
    id: 'C047',
    courseName: 'ADVANCE DATABASE MANAGEMENT SYSTEMS',
    courseCode: 'CSC221',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 44,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. NIDA ZAINAB',
  ),
  AssessmentCourse(
    id: 'C048',
    courseName: 'THEORY OF AUTOMATA',
    courseCode: 'CSC220',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 44,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. ASIM SHAHZAD',
  ),
  AssessmentCourse(
    id: 'C049',
    courseName: 'ARTIFICIAL INTELLIGENE',
    courseCode: 'CC223',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 45,
    program: 'BSCS',
    session: 'S26',
    instructor: 'FARIA BIBI',
  ),
  AssessmentCourse(
    id: 'C050',
    courseName: 'COMPUTER ORGANIZATION & ASSEMBLY LANGUAGE',
    courseCode: 'CC222',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 44,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. NOSHABA KHAN',
  ),
  AssessmentCourse(
    id: 'C051',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CC221',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 44,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. UROOJ TARIQ',
  ),
  AssessmentCourse(
    id: 'C052',
    courseName: 'PROBABILITY & STATISTICS',
    courseCode: 'STAT118',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 44,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. ANEELA BIBI',
  ),
  AssessmentCourse(
    id: 'C053',
    courseName: 'PROBABILITY & STATISTICS',
    courseCode: 'STAT118',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 42,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. ANEELA BIBI',
  ),
  AssessmentCourse(
    id: 'C054',
    courseName: 'THEORY OF AUTOMATA',
    courseCode: 'CSC220',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 42,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. ASIM SHAHZAD',
  ),
  AssessmentCourse(
    id: 'C055',
    courseName: 'ARTIFICIAL INTELLIGENE',
    courseCode: 'CC223',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'FARIA BIBI',
  ),
  AssessmentCourse(
    id: 'C056',
    courseName: 'COMPUTER ORGANIZATION & ASSEMBLY LANGUAGE',
    courseCode: 'CC222',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 42,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. NOSHABA KHAN',
  ),
  AssessmentCourse(
    id: 'C057',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CC221',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. AROOBA AKHTAR',
  ),
  AssessmentCourse(
    id: 'C058',
    courseName: 'ADVANCE DATABASE MANAGEMENT SYSTEMS',
    courseCode: 'CSC221',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. NIDA ZAINAB',
  ),
  AssessmentCourse(
    id: 'C059',
    courseName: 'PROBABILITY & STATISTICS',
    courseCode: 'STAT118',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. ANEELA BIBI',
  ),
  AssessmentCourse(
    id: 'C060',
    courseName: 'THEORY OF AUTOMATA',
    courseCode: 'CSC220',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. AAMER KHAN',
  ),
  AssessmentCourse(
    id: 'C061',
    courseName: 'ARTIFICIAL INTELLIGENE',
    courseCode: 'CC223',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'FARIA BIBI',
  ),
  AssessmentCourse(
    id: 'C062',
    courseName: 'COMPUTER ORGANIZATION & ASSEMBLY LANGUAGE',
    courseCode: 'CC222',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. ASAD IQBAL',
  ),
  AssessmentCourse(
    id: 'C063',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CC221',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. AROOBA AKHTAR',
  ),
  AssessmentCourse(
    id: 'C064',
    courseName: 'ADVANCE DATABASE MANAGEMENT SYSTEMS',
    courseCode: 'CSC221',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. NIDA ZAINAB',
  ),
  AssessmentCourse(
    id: 'C065',
    courseName: 'PROBABILITY & STATISTICS',
    courseCode: 'STAT118',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. ANEELA BIBI',
  ),
  AssessmentCourse(
    id: 'C066',
    courseName: 'THEORY OF AUTOMATA',
    courseCode: 'CSC220',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. AAMER KHAN',
  ),
  AssessmentCourse(
    id: 'C067',
    courseName: 'ARTIFICIAL INTELLIGENE',
    courseCode: 'CC223',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. UROOJ TARIQ',
  ),
  AssessmentCourse(
    id: 'C068',
    courseName: 'COMPUTER ORGANIZATION & ASSEMBLY LANGUAGE',
    courseCode: 'CC222',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. ASAD IQBAL',
  ),
  AssessmentCourse(
    id: 'C069',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CC221',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. AROOBA AKHTAR',
  ),
  AssessmentCourse(
    id: 'C070',
    courseName: 'ADVANCE DATABASE MANAGEMENT SYSTEMS',
    courseCode: 'CSC221',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. NIDA ZAINAB',
  ),
  AssessmentCourse(
    id: 'C071',
    courseName: 'ARTIFICIAL INTELLIGENCE',
    courseCode: 'CSC361',
    credits: 4,
    semester: '4',
    section: 'D',
    enrolledStudents: 3,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. UROOJ TARIQ',
  ),
  AssessmentCourse(
    id: 'C072',
    courseName: 'CLOUD COMPUTING',
    courseCode: 'CSE311',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. YOUSRA REHMAN',
  ),
  AssessmentCourse(
    id: 'C073',
    courseName: 'MANAGEMENT INFORMATION SYSTEMS',
    courseCode: 'CSE310',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. MARIA JADOON',
  ),
  AssessmentCourse(
    id: 'C074',
    courseName: 'COMPUTER ARCHITECTURE',
    courseCode: 'CSC311',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. UBAID UR REHMAN',
  ),
  AssessmentCourse(
    id: 'C075',
    courseName: 'HCI & COMPUTER GRAPHICS',
    courseCode: 'CSC310',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. UBAID UR REHMAN',
  ),
  AssessmentCourse(
    id: 'C076',
    courseName: 'OPERATING SYSTEMS',
    courseCode: 'CC310',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 46,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD IMRAN KHAN',
  ),
  AssessmentCourse(
    id: 'C077',
    courseName: 'INTRODUCTION TO PSYCHOLOGY',
    courseCode: 'PSY111',
    credits: 2,
    semester: '5',
    section: 'A',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. SAJIDA',
  ),
  AssessmentCourse(
    id: 'C078',
    courseName: 'PSYCHOLOGY',
    courseCode: 'PSY111',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 6,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. SAJIDA',
  ),
  AssessmentCourse(
    id: 'C079',
    courseName: 'OPERATING SYSTEM',
    courseCode: 'CSC242',
    credits: 4,
    semester: '5',
    section: 'A',
    enrolledStudents: 9,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. MUHAMMAD IMRAN KHAN',
  ),
  AssessmentCourse(
    id: 'C080',
    courseName: 'COMPILER CONSTRUCTION',
    courseCode: 'CSC320',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. ASAD IQBAL',
  ),
  AssessmentCourse(
    id: 'C081',
    courseName: 'PARALLEL & DISTRIBUTED COMPUTING',
    courseCode: 'CSC321',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'SYEDA KINZA NAQVI',
  ),
  AssessmentCourse(
    id: 'C082',
    courseName: 'ADVANCED PROGRAMMING',
    courseCode: 'CSE320',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 44,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. UBAID UR REHMAN',
  ),
  AssessmentCourse(
    id: 'C083',
    courseName: 'DIGITAL IMAGE PROCESSING',
    courseCode: 'CSE322',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. MARIA JADOON',
  ),
  AssessmentCourse(
    id: 'C084',
    courseName: 'DATA MINING',
    courseCode: 'CSE323',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 44,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. GOHAR ZAMAN',
  ),
  AssessmentCourse(
    id: 'C085',
    courseName: 'FINAL YEAR PROJECT (FYP)– I',
    courseCode: 'CSC500',
    credits: 2,
    semester: '6',
    section: 'A',
    enrolledStudents: 46,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
  AssessmentCourse(
    id: 'C086',
    courseName: 'COMPILER CONSTRUCTION',
    courseCode: 'CSC320',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 51,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. ASAD IQBAL',
  ),
  AssessmentCourse(
    id: 'C087',
    courseName: 'PARALLEL & DISTRIBUTED COMPUTING',
    courseCode: 'CSC321',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 51,
    program: 'BSCS',
    session: 'S26',
    instructor: 'SYEDA KINZA NAQVI',
  ),
  AssessmentCourse(
    id: 'C088',
    courseName: 'ADVANCED PROGRAMMING',
    courseCode: 'CSE320',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 51,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. UBAID UR REHMAN',
  ),
  AssessmentCourse(
    id: 'C089',
    courseName: 'DIGITAL IMAGE PROCESSING',
    courseCode: 'CSE322',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 51,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. MARIA JADOON',
  ),
  AssessmentCourse(
    id: 'C090',
    courseName: 'DATA MINING',
    courseCode: 'CSE323',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 51,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. AYESHA ASLAM',
  ),
  AssessmentCourse(
    id: 'C091',
    courseName: 'FINAL YEAR PROJECT (FYP)– I',
    courseCode: 'CSC500',
    credits: 2,
    semester: '6',
    section: 'B',
    enrolledStudents: 56,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
  AssessmentCourse(
    id: 'C092',
    courseName: 'COMPILER CONSTRUCTION',
    courseCode: 'CSC320',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 55,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. ASAD IQBAL',
  ),
  AssessmentCourse(
    id: 'C093',
    courseName: 'PARALLEL & DISTRIBUTED COMPUTING',
    courseCode: 'CSC321',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 52,
    program: 'BSCS',
    session: 'S26',
    instructor: 'SYEDA KINZA NAQVI',
  ),
  AssessmentCourse(
    id: 'C094',
    courseName: 'ADVANCED PROGRAMMING',
    courseCode: 'CSE320',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 55,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. UBAID UR REHMAN',
  ),
  AssessmentCourse(
    id: 'C095',
    courseName: 'DIGITAL IMAGE PROCESSING',
    courseCode: 'CSE322',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 55,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. MARIA JADOON',
  ),
  AssessmentCourse(
    id: 'C096',
    courseName: 'DATA MINING',
    courseCode: 'CSE323',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 55,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. AYESHA ASLAM',
  ),
  AssessmentCourse(
    id: 'C097',
    courseName: 'FINAL YEAR PROJECT (FYP)– I',
    courseCode: 'CSC500',
    credits: 2,
    semester: '6',
    section: 'C',
    enrolledStudents: 58,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
  AssessmentCourse(
    id: 'C098',
    courseName: 'FUNDAMENTALS OF DATA MINING',
    courseCode: 'CSC363',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 7,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. AYESHA ASLAM',
  ),
  AssessmentCourse(
    id: 'C099',
    courseName: 'SOFTWARE PROJECT MANAGEMENT',
    courseCode: 'CSC471',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 39,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. NAVEEDA BIBI',
  ),
  AssessmentCourse(
    id: 'C100',
    courseName: 'FINAL YEAR PROJECT (FYP) - I',
    courseCode: 'CSC500',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 38,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. ASIM ZEB',
  ),
  AssessmentCourse(
    id: 'C101',
    courseName: 'DIGITAL IMAGE PROCESSING',
    courseCode: 'CSC474',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 41,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. MAH-E-NOOR',
  ),
  AssessmentCourse(
    id: 'C102',
    courseName: 'NETWORK SECURITY',
    courseCode: 'CSC475',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'SYEDA KINZA NAQVI',
  ),
  AssessmentCourse(
    id: 'C103',
    courseName: 'PARALLEL AND DISTRIBUTED COMPUTING',
    courseCode: 'CSC472',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 38,
    program: 'BSCS',
    session: 'S26',
    instructor: 'SYEDA KINZA NAQVI',
  ),
  AssessmentCourse(
    id: 'C104',
    courseName: 'WIRELESS NETWORK SECURITY',
    courseCode: 'CSC473',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 3,
    program: 'BSCS',
    session: 'S26',
    instructor: 'SYEDA KINZA NAQVI',
  ),
  AssessmentCourse(
    id: 'C105',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CSC481',
    credits: 3,
    semester: '8',
    section: 'A',
    enrolledStudents: 35,
    program: 'BSCS',
    session: 'S26',
    instructor: 'FARIA BIBI',
  ),
  AssessmentCourse(
    id: 'C106',
    courseName: 'FINAL YEAR PROJECT (FYP) - II',
    courseCode: 'CSC500',
    credits: 3,
    semester: '8',
    section: 'A',
    enrolledStudents: 35,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. GOHAR ZAMAN',
  ),
  AssessmentCourse(
    id: 'C107',
    courseName: 'THEORY OF PROGRAMMING LANGUAGES',
    courseCode: 'CSC482',
    credits: 3,
    semester: '8',
    section: 'A',
    enrolledStudents: 35,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. SHANZA MEHBOOB',
  ),
  AssessmentCourse(
    id: 'C108',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CSC481',
    credits: 3,
    semester: '8',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'FARIA BIBI',
  ),
  AssessmentCourse(
    id: 'C109',
    courseName: 'FINAL YEAR PROJECT (FYP) - II',
    courseCode: 'CSC500',
    credits: 3,
    semester: '8',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'DR. GOHAR ZAMAN',
  ),
  AssessmentCourse(
    id: 'C110',
    courseName: 'THEORY OF PROGRAMMING LANGUAGES',
    courseCode: 'CSC482',
    credits: 3,
    semester: '8',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. SHANZA MEHBOOB',
  ),
  AssessmentCourse(
    id: 'C111',
    courseName: 'PROFESSIONAL PRACTICES',
    courseCode: 'CSC470',
    credits: 3,
    semester: '8',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MS. MAH-E-NOOR',
  ),
  AssessmentCourse(
    id: 'C112',
    courseName: 'PROFESSIONAL PRACTICES',
    courseCode: 'CSC470',
    credits: 3,
    semester: '8',
    section: 'A',
    enrolledStudents: 35,
    program: 'BSCS',
    session: 'S26',
    instructor: 'MR. AHSAN ZUBAIR',
  ),
  AssessmentCourse(
    id: 'C113',
    courseName: 'SOCIAL SCIENCE',
    courseCode: 'SS101',
    credits: 2,
    semester: '1',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. SANA GUL',
  ),
  AssessmentCourse(
    id: 'C114',
    courseName: 'ISLAMIC STUDIES (RELIGIOUS EDUCATION)',
    courseCode: 'IS101',
    credits: 2,
    semester: '1',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. INAMULLAH',
  ),
  AssessmentCourse(
    id: 'C115',
    courseName: 'QUANTITATIVE REASONING-I',
    courseCode: 'QR101',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. SAJID ALI',
  ),
  AssessmentCourse(
    id: 'C116',
    courseName: 'FAHM-E-QURAN',
    courseCode: 'FQ101',
    credits: 1,
    semester: '1',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. MUHAMMAD UMAIR',
  ),
  AssessmentCourse(
    id: 'C117',
    courseName: 'PROGRAMMING FUNDAMENTALS',
    courseCode: 'PF101',
    credits: 4,
    semester: '1',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'FARIA BIBI',
  ),
  AssessmentCourse(
    id: 'C118',
    courseName: 'APPLICATIONS OF INFORMATION AND COMMUNICATION TECHNOLOGIES',
    courseCode: 'AICT101',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MUQADDAS YOUSAF',
  ),
  AssessmentCourse(
    id: 'C119',
    courseName: 'ADDITIONAL MATH-I (FOR PRE-MEDICAL STUDENTS ONLY)',
    courseCode: 'AM101',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 23,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. SAJID ALI',
  ),
  AssessmentCourse(
    id: 'C120',
    courseName: 'FUNCTIONAL ENGLISH',
    courseCode: 'FE101',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. FATIMA MALIK',
  ),
  AssessmentCourse(
    id: 'C121',
    courseName: 'PROGRAMMING FUNDAMENTALS',
    courseCode: 'CSC 112',
    credits: 4,
    semester: '1',
    section: 'A',
    enrolledStudents: 3,
    program: 'BSSE',
    session: 'S26',
    instructor: 'FARIA BIBI',
  ),
  AssessmentCourse(
    id: 'C122',
    courseName: 'PROGRAMMING FUNDAMENTALS',
    courseCode: 'CC110',
    credits: 4,
    semester: '1',
    section: 'A',
    enrolledStudents: 2,
    program: 'BSSE',
    session: 'S26',
    instructor: 'FARIA BIBI',
  ),
  AssessmentCourse(
    id: 'C123',
    courseName: 'CALCULUS & ANALYTICAL GEOMETRY',
    courseCode: 'MAT118',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 19,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. SAJID ALI',
  ),
  AssessmentCourse(
    id: 'C124',
    courseName: 'FUNCTIONAL ENGLISH',
    courseCode: 'GE112',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 2,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. FATIMA MALIK',
  ),
  AssessmentCourse(
    id: 'C125',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CC120',
    credits: 4,
    semester: '2',
    section: 'A',
    enrolledStudents: 56,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. KINZA KHURSHID',
  ),
  AssessmentCourse(
    id: 'C126',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CC121',
    credits: 4,
    semester: '2',
    section: 'A',
    enrolledStudents: 56,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. AHSAN ZUBAIR',
  ),
  AssessmentCourse(
    id: 'C127',
    courseName: 'DIGITAL LOGIC DESIGN',
    courseCode: 'CC122',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 56,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. HADIYA ALI',
  ),
  AssessmentCourse(
    id: 'C128',
    courseName: 'EXPOSITORY WRITING',
    courseCode: 'GE120',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 56,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. IQRA MAHEEN',
  ),
  AssessmentCourse(
    id: 'C129',
    courseName: 'LINEAR ALGEBRA',
    courseCode: 'MAT232',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 54,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. RUKHSANA JABEEN',
  ),
  AssessmentCourse(
    id: 'C130',
    courseName: 'MATHEMATICS-II',
    courseCode: 'MAT111',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 9,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. ROMANA',
  ),
  AssessmentCourse(
    id: 'C131',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CC120',
    credits: 4,
    semester: '2',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. KINZA KHURSHID',
  ),
  AssessmentCourse(
    id: 'C132',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CC120',
    credits: 4,
    semester: '2',
    section: 'C',
    enrolledStudents: 44,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. MUHAMMAD SIBT UL HASSAN',
  ),
  AssessmentCourse(
    id: 'C133',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CC120',
    credits: 4,
    semester: '2',
    section: 'D',
    enrolledStudents: 47,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. MUHAMMAD SIBT UL HASSAN',
  ),
  AssessmentCourse(
    id: 'C134',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CC121',
    credits: 4,
    semester: '2',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSSE',
    session: 'S26',
    instructor: 'SOHAIR SULTAN',
  ),
  AssessmentCourse(
    id: 'C135',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CC121',
    credits: 4,
    semester: '2',
    section: 'C',
    enrolledStudents: 45,
    program: 'BSSE',
    session: 'S26',
    instructor: 'SOHAIR SULTAN',
  ),
  AssessmentCourse(
    id: 'C136',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CC121',
    credits: 4,
    semester: '2',
    section: 'D',
    enrolledStudents: 48,
    program: 'BSSE',
    session: 'S26',
    instructor: 'SOHAIR SULTAN',
  ),
  AssessmentCourse(
    id: 'C137',
    courseName: 'DIGITAL LOGIC DESIGN',
    courseCode: 'CC122',
    credits: 3,
    semester: '2',
    section: 'B',
    enrolledStudents: 43,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. HADIYA ALI',
  ),
  AssessmentCourse(
    id: 'C138',
    courseName: 'DIGITAL LOGIC DESIGN',
    courseCode: 'CC122',
    credits: 3,
    semester: '2',
    section: 'C',
    enrolledStudents: 45,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. HADIYA ALI',
  ),
  AssessmentCourse(
    id: 'C139',
    courseName: 'DIGITAL LOGIC DESIGN',
    courseCode: 'CC122',
    credits: 3,
    semester: '2',
    section: 'D',
    enrolledStudents: 48,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. HADIYA ALI',
  ),
  AssessmentCourse(
    id: 'C140',
    courseName: 'EXPOSITORY WRITING',
    courseCode: 'GE120',
    credits: 3,
    semester: '2',
    section: 'B',
    enrolledStudents: 41,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. SAMMAR AYAZ',
  ),
  AssessmentCourse(
    id: 'C141',
    courseName: 'EXPOSITORY WRITING',
    courseCode: 'GE120',
    credits: 3,
    semester: '2',
    section: 'C',
    enrolledStudents: 45,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. LARAIB KHAN',
  ),
  AssessmentCourse(
    id: 'C142',
    courseName: 'EXPOSITORY WRITING',
    courseCode: 'GE120',
    credits: 3,
    semester: '2',
    section: 'D',
    enrolledStudents: 48,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. ABDUL AMAN',
  ),
  AssessmentCourse(
    id: 'C143',
    courseName: 'LINEAR ALGEBRA',
    courseCode: 'MAT232',
    credits: 3,
    semester: '2',
    section: 'B',
    enrolledStudents: 40,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. SAJID ALI',
  ),
  AssessmentCourse(
    id: 'C144',
    courseName: 'LINEAR ALGEBRA',
    courseCode: 'MAT232',
    credits: 3,
    semester: '2',
    section: 'C',
    enrolledStudents: 40,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. RUKHSANA JABEEN',
  ),
  AssessmentCourse(
    id: 'C145',
    courseName: 'LINEAR ALGEBRA',
    courseCode: 'MAT232',
    credits: 3,
    semester: '2',
    section: 'D',
    enrolledStudents: 49,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. RUKHSANA JABEEN',
  ),
  AssessmentCourse(
    id: 'C146',
    courseName: 'MATHEMATICS-II',
    courseCode: 'MAT111',
    credits: 3,
    semester: '2',
    section: 'B',
    enrolledStudents: 9,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. ROMANA',
  ),
  AssessmentCourse(
    id: 'C147',
    courseName: 'MATHEMATICS-II',
    courseCode: 'MAT111',
    credits: 3,
    semester: '2',
    section: 'C',
    enrolledStudents: 3,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. ROMANA',
  ),
  AssessmentCourse(
    id: 'C148',
    courseName: 'MATHEMATICS-II',
    courseCode: 'MAT111',
    credits: 3,
    semester: '2',
    section: 'D',
    enrolledStudents: 6,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. ROMANA',
  ),
  AssessmentCourse(
    id: 'C149',
    courseName: 'OBJECT ORIENTED PROGRAMMING',
    courseCode: 'CSC 121',
    credits: 4,
    semester: '2',
    section: 'D',
    enrolledStudents: 6,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. MUHAMMAD SIBT UL HASSAN',
  ),
  AssessmentCourse(
    id: 'C150',
    courseName: 'DATABASE SYSTEMS',
    courseCode: 'CSC241',
    credits: 4,
    semester: '2',
    section: 'D',
    enrolledStudents: 10,
    program: 'BSSE',
    session: 'S26',
    instructor: 'SOHAIR SULTAN',
  ),
  AssessmentCourse(
    id: 'C151',
    courseName: 'DISCRETE STRUCTURES',
    courseCode: 'GE101',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. AYESHA ASLAM',
  ),
  AssessmentCourse(
    id: 'C152',
    courseName: 'MULTIVARIABLE CALCULUS',
    courseCode: 'MAT237',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. RUKHSANA JABEEN',
  ),
  AssessmentCourse(
    id: 'C153',
    courseName: 'SOFTWARE ENGINEERING',
    courseCode: 'CC214',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 35,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
  AssessmentCourse(
    id: 'C154',
    courseName: 'COMPUTER NETWORKS',
    courseCode: 'CC213',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. HADIYA ALI',
  ),
  AssessmentCourse(
    id: 'C155',
    courseName: 'DATA STRUCTURES',
    courseCode: 'CC210',
    credits: 4,
    semester: '3',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'SOHAIR SULTAN',
  ),
  AssessmentCourse(
    id: 'C156',
    courseName: 'ISLAMIC STUDIES',
    courseCode: 'GE220',
    credits: 2,
    semester: '3',
    section: 'A',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. INAMULLAH',
  ),
  AssessmentCourse(
    id: 'C157',
    courseName: 'SOFTWARE ENGINEERING',
    courseCode: 'CSC 122',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 5,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
  AssessmentCourse(
    id: 'C158',
    courseName: 'DATA STRUCTURES AND ALGORITHMS',
    courseCode: 'CSC-231',
    credits: 4,
    semester: '3',
    section: 'A',
    enrolledStudents: 19,
    program: 'BSSE',
    session: 'S26',
    instructor: 'SOHAIR SULTAN',
  ),
  AssessmentCourse(
    id: 'C159',
    courseName: 'DISCRETE STRUCTURES',
    courseCode: 'CSC 123',
    credits: 3,
    semester: '3',
    section: 'A',
    enrolledStudents: 1,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. AYESHA ASLAM',
  ),
  AssessmentCourse(
    id: 'C160',
    courseName: 'COMPUTER NETWORKS',
    courseCode: 'CSC351',
    credits: 4,
    semester: '3',
    section: 'A',
    enrolledStudents: 1,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. HADIYA ALI',
  ),
  AssessmentCourse(
    id: 'C161',
    courseName: 'SOFTWARE DESIGN & ARCHITECTURE',
    courseCode: 'SEDC221',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 50,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. AROOBA AKHTAR',
  ),
  AssessmentCourse(
    id: 'C162',
    courseName: 'SOFTWARE CONSTRUCTION & DEVELOPMENT',
    courseCode: 'SEDC220',
    credits: 4,
    semester: '4',
    section: 'A',
    enrolledStudents: 50,
    program: 'BSSE',
    session: 'S26',
    instructor: 'SYEDA KINZA NAQVI',
  ),
  AssessmentCourse(
    id: 'C163',
    courseName: 'COMPUTER ORGANIZATION & ASSEMBLY LANGUAGE',
    courseCode: 'CC215',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 50,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. UBAID UR REHMAN',
  ),
  AssessmentCourse(
    id: 'C164',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CC211',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 50,
    program: 'BSSE',
    session: 'S26',
    instructor: 'SYEDA KINZA NAQVI',
  ),
  AssessmentCourse(
    id: 'C165',
    courseName: 'ARTIFICIAL INTELLIGENE',
    courseCode: 'CC212',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 50,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD SHEHZAD KHAN',
  ),
  AssessmentCourse(
    id: 'C166',
    courseName: 'PROBABILITY & STATISTICS',
    courseCode: 'STAT118',
    credits: 3,
    semester: '4',
    section: 'A',
    enrolledStudents: 50,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. ANEELA BIBI',
  ),
  AssessmentCourse(
    id: 'C167',
    courseName: 'SOFTWARE CONSTRUCTION & DEVELOPMENT',
    courseCode: 'SEDC220',
    credits: 4,
    semester: '4',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MEHWISH SARWAR',
  ),
  AssessmentCourse(
    id: 'C168',
    courseName: 'COMPUTER ORGANIZATION & ASSEMBLY LANGUAGE',
    courseCode: 'CC215',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. ASAD IQBAL',
  ),
  AssessmentCourse(
    id: 'C169',
    courseName: 'PROBABILITY & STATISTICS',
    courseCode: 'STAT118',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. KHOLA ZAHOOR',
  ),
  AssessmentCourse(
    id: 'C170',
    courseName: 'SOFTWARE DESIGN & ARCHITECTURE',
    courseCode: 'SEDC221',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. AROOBA AKHTAR',
  ),
  AssessmentCourse(
    id: 'C171',
    courseName: 'ARTIFICIAL INTELLIGENE',
    courseCode: 'CC212',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD SHEHZAD KHAN',
  ),
  AssessmentCourse(
    id: 'C172',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CC211',
    credits: 3,
    semester: '4',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. UROOJ TARIQ',
  ),
  AssessmentCourse(
    id: 'C173',
    courseName: 'SOFTWARE CONSTRUCTION & DEVELOPMENT',
    courseCode: 'SEDC220',
    credits: 4,
    semester: '4',
    section: 'C',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MEHWISH SARWAR',
  ),
  AssessmentCourse(
    id: 'C174',
    courseName: 'COMPUTER ORGANIZATION & ASSEMBLY LANGUAGE',
    courseCode: 'CC215',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. UBAID UR REHMAN',
  ),
  AssessmentCourse(
    id: 'C175',
    courseName: 'PROBABILITY & STATISTICS',
    courseCode: 'STAT118',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. KHOLA ZAHOOR',
  ),
  AssessmentCourse(
    id: 'C176',
    courseName: 'SOFTWARE DESIGN & ARCHITECTURE',
    courseCode: 'SEDC221',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. AROOBA AKHTAR',
  ),
  AssessmentCourse(
    id: 'C177',
    courseName: 'ARTIFICIAL INTELLIGENE',
    courseCode: 'CC212',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD SHEHZAD KHAN',
  ),
  AssessmentCourse(
    id: 'C178',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CC211',
    credits: 3,
    semester: '4',
    section: 'C',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. UROOJ TARIQ',
  ),
  AssessmentCourse(
    id: 'C179',
    courseName: 'SOFTWARE CONSTRUCTION & DEVELOPMENT',
    courseCode: 'SEDC220',
    credits: 4,
    semester: '4',
    section: 'D',
    enrolledStudents: 51,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MEHWISH SARWAR',
  ),
  AssessmentCourse(
    id: 'C180',
    courseName: 'COMPUTER ORGANIZATION & ASSEMBLY LANGUAGE',
    courseCode: 'CC215',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 51,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. NOSHABA KHAN',
  ),
  AssessmentCourse(
    id: 'C181',
    courseName: 'PROBABILITY & STATISTICS',
    courseCode: 'STAT118',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 50,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. KHOLA ZAHOOR',
  ),
  AssessmentCourse(
    id: 'C182',
    courseName: 'SOFTWARE DESIGN & ARCHITECTURE',
    courseCode: 'SEDC221',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 51,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MAH-E-NOOR',
  ),
  AssessmentCourse(
    id: 'C183',
    courseName: 'ARTIFICIAL INTELLIGENE',
    courseCode: 'CC212',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 51,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. NIDA ZAINAB',
  ),
  AssessmentCourse(
    id: 'C184',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CC211',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 51,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. UROOJ TARIQ',
  ),
  AssessmentCourse(
    id: 'C185',
    courseName: 'SOFTWARE DESIGN AND ARCHITECTURE',
    courseCode: 'SEC243',
    credits: 3,
    semester: '4',
    section: 'D',
    enrolledStudents: 2,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MAH-E-NOOR',
  ),
  AssessmentCourse(
    id: 'C186',
    courseName: 'SOFTWARE ENGINEERING ECONOMICS',
    courseCode: 'SEE311',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 39,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. NIDA ZAINAB',
  ),
  AssessmentCourse(
    id: 'C187',
    courseName: 'AGENT BASED SOFTWARE ENGINEERING',
    courseCode: 'SEE310',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 39,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. UBAID UR REHMAN',
  ),
  AssessmentCourse(
    id: 'C188',
    courseName: 'SOFTWARE REQUIREMENT ENGINEERING',
    courseCode: 'SEC312',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 39,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MEHWISH SARWAR',
  ),
  AssessmentCourse(
    id: 'C189',
    courseName: 'SOFTWARE QUALITY ENGINEERING',
    courseCode: 'SEC311',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 39,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MEHWISH SARWAR',
  ),
  AssessmentCourse(
    id: 'C190',
    courseName: 'OPERATING SYSTEMS',
    courseCode: 'CC310',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 39,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. MUHAMMAD IMRAN KHAN',
  ),
  AssessmentCourse(
    id: 'C191',
    courseName: 'INTRODUCTION TO PSYCHOLOGY',
    courseCode: 'PSY111',
    credits: 2,
    semester: '5',
    section: 'A',
    enrolledStudents: 39,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. SAJIDA',
  ),
  AssessmentCourse(
    id: 'C192',
    courseName: 'SOFTWARE REQUIREMENT ENGINEERING',
    courseCode: 'SEC232',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 4,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MEHWISH SARWAR',
  ),
  AssessmentCourse(
    id: 'C193',
    courseName: 'SOFTWARE QUALITY ENGINEERING',
    courseCode: 'SEC361',
    credits: 3,
    semester: '5',
    section: 'A',
    enrolledStudents: 1,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MEHWISH SARWAR',
  ),
  AssessmentCourse(
    id: 'C194',
    courseName: 'SOFTWARE PROJECT MANAGEMENT',
    courseCode: 'SEDC310',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. SHANZA MEHBOOB',
  ),
  AssessmentCourse(
    id: 'C195',
    courseName: 'PARALLEL & DISTRIBUTED COMPUTING',
    courseCode: 'SEDC320',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MAH-E-NOOR',
  ),
  AssessmentCourse(
    id: 'C196',
    courseName: 'MANAGEMENT INFORMATION SYSTEM',
    courseCode: 'SEE320',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MIR JAMAL UD DIN',
  ),
  AssessmentCourse(
    id: 'C197',
    courseName: 'E-COMMERCE',
    courseCode: 'SEE321',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MUQADDAS YOUSAF',
  ),
  AssessmentCourse(
    id: 'C198',
    courseName: 'SOFTWARE METRICS',
    courseCode: 'SEE322',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. YOUSRA REHMAN',
  ),
  AssessmentCourse(
    id: 'C199',
    courseName: 'DATA SCIENCE',
    courseCode: 'SEE 323',
    credits: 3,
    semester: '6',
    section: 'A',
    enrolledStudents: 53,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. FAHAD ALI KHAN',
  ),
  AssessmentCourse(
    id: 'C200',
    courseName: 'FINAL YEAR PROJECT (FYP)– I',
    courseCode: 'CSC500',
    credits: 2,
    semester: '6',
    section: 'A',
    enrolledStudents: 55,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
  AssessmentCourse(
    id: 'C201',
    courseName: 'SOFTWARE PROJECT MANAGEMENT',
    courseCode: 'SEDC310',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 49,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. SHANZA MEHBOOB',
  ),
  AssessmentCourse(
    id: 'C202',
    courseName: 'SOFTWARE PROJECT MANAGEMENT',
    courseCode: 'SEDC310',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 37,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. SHANZA MEHBOOB',
  ),
  AssessmentCourse(
    id: 'C203',
    courseName: 'PARALLEL & DISTRIBUTED COMPUTING',
    courseCode: 'SEDC320',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 49,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MAH-E-NOOR',
  ),
  AssessmentCourse(
    id: 'C204',
    courseName: 'PARALLEL & DISTRIBUTED COMPUTING',
    courseCode: 'SEDC320',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MAH-E-NOOR',
  ),
  AssessmentCourse(
    id: 'C205',
    courseName: 'MANAGEMENT INFORMATION SYSTEM',
    courseCode: 'SEE320',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. SHANZA MEHBOOB',
  ),
  AssessmentCourse(
    id: 'C206',
    courseName: 'MANAGEMENT INFORMATION SYSTEM',
    courseCode: 'SEE320',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 49,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MIR JAMAL UD DIN',
  ),
  AssessmentCourse(
    id: 'C207',
    courseName: 'E-COMMERCE',
    courseCode: 'SEE321',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 49,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MUQADDAS YOUSAF',
  ),
  AssessmentCourse(
    id: 'C208',
    courseName: 'E-COMMERCE',
    courseCode: 'SEE321',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MUQADDAS YOUSAF',
  ),
  AssessmentCourse(
    id: 'C209',
    courseName: 'SOFTWARE METRICS',
    courseCode: 'SEE322',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. YOUSRA REHMAN',
  ),
  AssessmentCourse(
    id: 'C210',
    courseName: 'SOFTWARE METRICS',
    courseCode: 'SEE322',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 49,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. YOUSRA REHMAN',
  ),
  AssessmentCourse(
    id: 'C211',
    courseName: 'DATA SCIENCE',
    courseCode: 'SEE 323',
    credits: 3,
    semester: '6',
    section: 'B',
    enrolledStudents: 49,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. FAHAD ALI KHAN',
  ),
  AssessmentCourse(
    id: 'C212',
    courseName: 'DATA SCIENCE',
    courseCode: 'SEE 323',
    credits: 3,
    semester: '6',
    section: 'C',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. FAHAD ALI KHAN',
  ),
  AssessmentCourse(
    id: 'C213',
    courseName: 'FINAL YEAR PROJECT (FYP)– I',
    courseCode: 'CSC500',
    credits: 2,
    semester: '6',
    section: 'C',
    enrolledStudents: 36,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
  AssessmentCourse(
    id: 'C214',
    courseName: 'FINAL YEAR PROJECT (FYP)– I',
    courseCode: 'CSC500',
    credits: 2,
    semester: '6',
    section: 'B',
    enrolledStudents: 55,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
  AssessmentCourse(
    id: 'C215',
    courseName: 'SOFTWARE RE-ENGINEERING',
    courseCode: 'SEC472',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 21,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MIR JAMAL UD DIN',
  ),
  AssessmentCourse(
    id: 'C216',
    courseName: 'FINAL YEAR PROJECT - I',
    courseCode: 'CSC500',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 20,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. ASIM ZEB',
  ),
  AssessmentCourse(
    id: 'C217',
    courseName: 'PROFESSIONAL PRACTICES',
    courseCode: 'CSC470',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 22,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. AHSAN ZUBAIR',
  ),
  AssessmentCourse(
    id: 'C218',
    courseName: 'SOFTWARE PROJECT MANAGEMENT',
    courseCode: 'SEC471',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 22,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. NAVEEDA BIBI',
  ),
  AssessmentCourse(
    id: 'C219',
    courseName: 'FUNDAMENTALS OF CRYPTOGRAPHY',
    courseCode: 'SEC476',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 22,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MR. ASAD IQBAL',
  ),
  AssessmentCourse(
    id: 'C220',
    courseName: 'DIGITAL MARKETING',
    courseCode: 'SEC479',
    credits: 3,
    semester: '7',
    section: 'A',
    enrolledStudents: 25,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. ASIM SHAHZAD',
  ),
  AssessmentCourse(
    id: 'C221',
    courseName: 'FINAL YEAR PROJECT- II',
    courseCode: 'CSC500',
    credits: 3,
    semester: '8',
    section: 'A',
    enrolledStudents: 56,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. GOHAR ZAMAN',
  ),
  AssessmentCourse(
    id: 'C222',
    courseName: 'AGENTIC AI',
    courseCode: 'SEC487',
    credits: 3,
    semester: '8',
    section: 'A',
    enrolledStudents: 56,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. ASIM ZEB',
  ),
  AssessmentCourse(
    id: 'C223',
    courseName: 'FINAL YEAR PROJECT- II',
    courseCode: 'CSC500',
    credits: 3,
    semester: '8',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. GOHAR ZAMAN',
  ),
  AssessmentCourse(
    id: 'C224',
    courseName: 'AGENTIC AI',
    courseCode: 'SEC487',
    credits: 3,
    semester: '8',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. MARIA JADOON',
  ),
  AssessmentCourse(
    id: 'C225',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CSC481',
    credits: 3,
    semester: '8',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD ZEESHAN',
  ),
  AssessmentCourse(
    id: 'C226',
    courseName: 'INFORMATION SECURITY',
    courseCode: 'CSC481',
    credits: 3,
    semester: '8',
    section: 'A',
    enrolledStudents: 56,
    program: 'BSSE',
    session: 'S26',
    instructor: 'DR. MUHAMMAD ZEESHAN',
  ),
  AssessmentCourse(
    id: 'C227',
    courseName: 'PSYCHOLOGY',
    courseCode: 'PSY111',
    credits: 3,
    semester: '8',
    section: 'A',
    enrolledStudents: 56,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. TAYYABA NOOR QURESHI',
  ),
  AssessmentCourse(
    id: 'C228',
    courseName: 'PSYCHOLOGY',
    courseCode: 'PSY111',
    credits: 3,
    semester: '8',
    section: 'B',
    enrolledStudents: 57,
    program: 'BSSE',
    session: 'S26',
    instructor: 'MS. SAJIDA',
  ),
  AssessmentCourse(
    id: 'C229',
    courseName: 'ADVANCED COMPUTER ARCHITECTURE',
    courseCode: 'CSC522',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 0,
    program: 'MPCS',
    session: 'S26',
    instructor: 'DR. ASIM ZEB',
  ),
  AssessmentCourse(
    id: 'C230',
    courseName: 'ADVANCED OPERATING SYSTEMS',
    courseCode: 'CSC512',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 0,
    program: 'MPCS',
    session: 'S26',
    instructor: 'DR. MUHAMMAD SHEHZAD KHAN',
  ),
  AssessmentCourse(
    id: 'C231',
    courseName: 'ADVANCED CRYPTOGRAPHY',
    courseCode: 'CSC549',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 0,
    program: 'MPCS',
    session: 'S26',
    instructor: 'DR. MUHAMMAD ZEESHAN',
  ),
  AssessmentCourse(
    id: 'C232',
    courseName: 'LLM AGENTS',
    courseCode: 'LLM-101',
    credits: 3,
    semester: '1',
    section: 'A',
    enrolledStudents: 0,
    program: 'MPCS',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
  AssessmentCourse(
    id: 'C233',
    courseName: 'ADVANCED CRYPTOGRAPHY',
    courseCode: 'CSC549',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 16,
    program: 'MPCS',
    session: 'S26',
    instructor: 'DR. MUHAMMAD ZEESHAN',
  ),
  AssessmentCourse(
    id: 'C234',
    courseName: 'ADVANCED COMPUTER ARCHITECTURE',
    courseCode: 'CSC522',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 16,
    program: 'MPCS',
    session: 'S26',
    instructor: 'DR. ASIM ZEB',
  ),
  AssessmentCourse(
    id: 'C235',
    courseName: 'ADVANCED OPERATING SYSTEMS',
    courseCode: 'CSC512',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 16,
    program: 'MPCS',
    session: 'S26',
    instructor: 'DR. MUHAMMAD SHEHZAD KHAN',
  ),
  AssessmentCourse(
    id: 'C236',
    courseName: 'LLM AGENTS',
    courseCode: 'LLM-101',
    credits: 3,
    semester: '2',
    section: 'A',
    enrolledStudents: 16,
    program: 'MPCS',
    session: 'S26',
    instructor: 'DR. MUHAMMAD NAEEM',
  ),
];

final registrationTeachers = _buildRegistrationTeachers(registrationCourses);

List<AssessmentTeacher> _buildRegistrationTeachers(
  List<AssessmentCourse> courses,
) {
  final courseIdsByTeacher = <String, List<String>>{};
  for (final course in courses) {
    courseIdsByTeacher
        .putIfAbsent(course.instructor, () => <String>[])
        .add(course.id);
  }

  final names = courseIdsByTeacher.keys.toList()..sort();
  return <AssessmentTeacher>[
    for (var index = 0; index < names.length; index++)
      AssessmentTeacher(
        id: 'T${(index + 1).toString().padLeft(3, '0')}',
        name: names[index],
        email: '${_teacherEmailSlug(names[index])}@assessment.local',
        password: '',
        courseIds: List.unmodifiable(courseIdsByTeacher[names[index]]!..sort()),
      ),
  ];
}

String _teacherEmailSlug(String value) {
  final normalized = value.toLowerCase().replaceAll(RegExp(r"[^a-z0-9]+"), '.');
  return normalized
      .replaceAll(RegExp(r'^mr|^ms|^dr|^prof'), '')
      .replaceAll(RegExp(r'^\.+|\.+$'), '');
}
